version: '3.8'
services:
  simulator1:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    entrypoint: ["/entrypoint.sh", "/simulator"]
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - SIMULATOR_ID=${SIMULATOR_ID1}
      - PERIOD=${PERIOD1}
    networks:
      - app-network

  simulator2:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    entrypoint: ["/entrypoint.sh", "/simulator"]
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - SIMULATOR_ID=${SIMULATOR_ID2}
      - PERIOD=${PERIOD2}
    networks:
      - app-network

  processor:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    entrypoint: ["/entrypoint.sh", "/processor"]
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_CONN_STR=${POSTGRES_CONN_STR}
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   # RabbitMQ server
      - "15672:15672" # RabbitMQ management UI
    networks:
      - app-network

  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./deployments/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
