apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maritime-equipment-simulator.fullname" . }}-secrets
type: Opaque
data:
  rabbitmq-url: {{ printf "amqp://%s:%s@%s-rabbitmq.default.svc.cluster.local:5672" .Values.rabbitmq.username .Values.rabbitmq.password (include "maritime-equipment-simulator.fullname" .) | b64enc }}
  postgres-url: {{ printf "postgresql://%s:%s@%s-postgresql.default.svc.cluster.local:5432/%s" .Values.postgresql.username .Values.postgresql.password (include "maritime-equipment-simulator.fullname" .) .Values.postgresql.database | b64enc }}
