name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: actions/setup-kubectl@v1
        with:
          version: v1.18.0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Deploy with Helm
        run: |
          helm upgrade --install simulator helm/ --namespace your-namespace --set image.tag=latest
